#!/usr/bin/env python3
#
# Autogenerated by 'shortcuts'
# ==================================================
# Edit /home/rtw/.local/share/shortcuts instead of this.

config.bind('xo', 'open https://odysee.com')
config.bind('xgh', 'open https://github.com')
config.bind('xgl', 'open https://gitlab.com')
config.bind('xwg', 'open https://4chan.org/wg/')
config.bind('xaur', 'open https://aur.archlinux.org')
config.bind('xaw', 'open https://wiki.archlinux.org')
config.bind('xko', 'open https://kernel.org')
config.bind('xgko', 'open https://git.kernel.org')
